Application applied failed due to wrong attribute 'id'
Fault Class/Object only has alarm_id, not id which cause sysinv crash
like "AttributeError: 'Fault' object has no attribute 'id'"

Change-Id: I4aaefc764f5fa13842cd60ee99752e497a3fd439
Closes-bug: 1892830
Signed-off-by: Austin Sun <austin.sun@intel.com>