Fix check_output return on Debian
Upgrade script 68 fails running on Debian with a TypeError:
TypeError: a bytes-like object is required, not 'str'

This issue is due to check_output returning different types
on python2 (string) and python3 (byte string).

This commit converts the returned byte string to a string.

Test Plan
PASS: run upgrade-activate successfully

Story: 2009303
Task: 47134

Change-Id: Ie1c5fd5ad445d9ee507d6ce6561ddb735f3c4578
Signed-off-by: Heitor Matsui <heitorvieira.matsui@windriver.com>