Fix missing request_timeout config option
Add request_timeout configuration option to openstack_keystone_opts
to fix NoSuchOptError when accessing
cfg.CONF[OPENSTACK_CONFIG].request_timeout.

The request_timeout option was previously added
https://review.opendev.org/c/starlingx/config/+/976269 only to
keystone_opts (KEYSTONE_AUTHTOKEN group) but was missing from
openstack_keystone_opts (OPENSTACK_KEYSTONE_AUTHTOKEN group),
causing runtime errors when _get_new_keystone_session() or
_get_keystone_session_for_sysinv() attempted to read the
timeout value for OPENSTACK_CONFIG.

Error observed:
  oslo_config.cfg.NoSuchOptError: no such option request_timeout in
  group [OPENSTACK_KEYSTONE_AUTHTOKEN]

This fix ensures both configuration groups have the request_timeout
option with a default value of 30 seconds to prevent indefinite
blocking on keystone API calls.

TestCases:
PASS: Notice no errors message of request_timeout option for
      periodic tasks

Closes-Bug: 2141433

Change-Id: Ib7dcf59c66a26f320e7dc9c741f3f6eca114faba
Signed-off-by: amantri <ayyappa.mantri@windriver.com>