DEV: Sysinv changes to support ptp4l unicast master tables
Implement functionality for users to create entries for
"unicast_master_table" in the ptp4l config.

- Input should be accepted as ptp4l instance's level parameter
- Each UMT will have to be uniquely identified when input so that
  the parameters can be associated to each other later during
  hieradata generation.
- Implement some degree of input validation in sysinv to keep
  parameters organized and correct
- A given ptp4l instance should be able to accept any number of
  unicast master table parameters with unique ids

PTP4l supports following parameters per unicast_master_table section:
table_id: unique, positive table ID
logQueryInterval: It is specified as a power of two in seconds.
peer_address: unicast address of the peer (IPv4 or IPv6)
L2|UDPv4|UDPv6: transport type and network address, multiple supported.

This commit:
- adds section column in ptp_parameters table
- gets user input for section value of PTP parameter as:
system ptp-instance-parameter-add/delete ptpinst1 --section
   <section-name> key=value
- The section is passed from client to server, by adding section on api.
- When user don't provide input for section, default value assumed global
  and gives backward compatibility for api.
- "system ptp-parameter-list" now shows section column too.
- "system ptp-instance-show ptpinst1" now shows sectional grouping of
  parameters, for better readablity.
- When section name has prefix of "unicast_master_table", parameters are
  checked against name and value, and also checked within new input and
  also against DB to support above requirement.

Unit tests are added to support new requirement.

TEST PLAN:
PASS: Deploy load with PTP4L and PHC2SYS instances
PASS: Check default section global on ptp-instance-parameter-add/delete
      - system ptp-instance-parameter-add ptpinst1 test=44
        Output shows: parameters {'global':[....., 'test=44'']}
      - system ptp-instance-show ptpinst1
        Same sectional grouping as above.
      - system ptp-instance-parameter-delete ptpinst1 test=44
        Output shows: parameters without 'test=44'
PASS: Check explicit section global on ptp-instance-parameter-add/delete
      - system ptp-instance-parameter-add ptpinst1 --section global
           domainNumber=44
        Output shows: parameters {'global':[....., 'domainNumber=44'']}
      - system ptp-instance-show ptpinst1
        Same sectional grouping as above.
      - system ptp-instance-parameter-delete ptpinst1 --section global
           domainNumber=44
        Output shows: parameters without 'domainNumber=44'
PASS: Check explicit section "random section" on ptp-instance-parameter-add/delete
      - system ptp-instance-parameter-add ptpinst1
           --section "random section" test1=44
      - system ptp-instance-parameter-add ptpinst1
           --section "random section" test2=xx test3=yy
      - Output shows: parameters {'global':[...], 'random section':
           ['test1=44', 'test2=xx', 'test3=yy']}
      - system ptp-instance-parameter-delete ptpinst1
           --section "random section" test2=xx
      - system ptp-instance-parameter-delete ptpinst1
           --section "random section" test1=44 test3=yy
      - Output shows: parameters {'global: [...]'}
      - system ptp-instance-parameter-delete ptpinst1
           --section "random section" test1=44 test3=yy
        shows: No PTP parameter object found for random
           section's test1=44
PASS: Check explicit section "unicast_master_section_1" on
      ptp-instance-parameter-add/delete
      - system ptp-instance-parameter-add ptpinst1
           --section unicast_master_table_1 table_x=2
        shows: Parameter table_x is not supported. Supported parameters:
           ['table_id','logQueryInterval', 'peer_address', 'L2',
           'UDPv4', 'UDPv6']
      - system ptp-instance-parameter-add ptpinst1 --section
           unicast_master_table_1 table_id=1
        logQueryInterval=-1 peer_address=::1 UDPv4=1.1.1.1 UDPv4=2.2.2.2
        Output shows: {'global':[...],  'unicast_master_table_1':
           ['table_id=1','logQueryInterval=-1', 'peer_address=::1',
           'UDPv4=1.1.1.1', 'UDPv4=2.2.2.2']}}
      - system ptp-instance-parameter-add ptpinst1 --section
           unicast_master_table_1 table_id=1
        Shows: already a PTP parameter..
      - system ptp-instance-parameter-add ptpinst1 --section
           unicast_master_table_1 table_id=2
        Shows: Parameter already exists: section:unicast_master_table_1
           parameter:table_id new value:2 vs existing value:1
      - system ptp-instance-parameter-add ptpinst1 --section
           unicast_master_table_1 logQueryInterval=2
        Shows: Parameter already exists: section:unicast_master_table_1
               parameter:logQueryInterval new value:2 vs existing value:-1
      - system ptp-instance-parameter-add ptpinst1 --section
           unicast_master_table_1 peer_address=::2
        Shows: Parameter already exists: section:unicast_master_table_1
           parameter:peer_address new value:::2 vs existing value:::1
      - system ptp-instance-parameter-add ptpinst1 --section
           unicast_master_table_1 UDPv4=3.3.3.3
        Output shows: {'global':[...],  'unicast_master_table_1': [
           'table_id=1','logQueryInterval=-1', 'peer_address=::1',
           'UDPv4=1.1.1.1', 'UDPv4=2.2.2.2', 'UDPv4=3.3.3.3']}}
      - system ptp-instance-parameter-add ptpinst1 --section
            unicast_master_table_1 UDPv6=::1
        Shows: L2 or UPPv4 or UDPv6 , these parameters can not be mixed,
              section: unicast_master_table_1, new parameter:UDPv6 vs
              existing parameter:UDPv4
PASS: Check explicit section "unicast_master_section_2" on
            ptp-instance-parameter-add/delete
      - system ptp-instance-parameter-add ptpinst1 --section
            unicast_master_table_2 table_id=1
       Shows: table_id=1 is not unique, already exist in unicast_master_table_1
      - system ptp-instance-parameter-add ptpinst1 --section
            unicast_master_table_2 table_id=0
        Shows: Bad PTP parameter keypair: table_id=0
               error: not positive integer
      - system ptp-instance-parameter-add ptpinst1 --section
            unicast_master_table_2 logQueryInterval=xx
        Shows: Bad PTP parameter keypair: logQueryInterval=xx
               error: not integer
      - system ptp-instance-parameter-add ptpinst1 --section
            unicast_master_table_2 peer_address=xx
        Shows: Bad PTP parameter keypair: peer_address=xx
               error: not IPv4/6 address
      - system ptp-instance-parameter-add ptpinst1 --section
            unicast_master_table_2 UDPv4=1.2
       Shows: Bad PTP parameter keypair: UDPv4=1.2
              error: not IPv4 address
      - system ptp-instance-parameter-add ptpinst1 --section
            unicast_master_table_2 UDPv6=1.2
        Shows: Bad PTP parameter keypair: UDPv6=1.2
               error: not IPv6 address
      - system ptp-instance-parameter-add ptpinst1 --section
            unicast_master_table_2 L2=00:00:00:00:00:01 UDPv4=1.2.3.4
        Shows: Bad PTP parameter keypair, error: L2 or UPPv4 or UDPv6,
               these parameters can not be mixed

PASS: "system ptp-parameter-list" shows section column
PASS: "system ptp-instance-apply" and nothing changed on ptp configurations

Story: 2011536
Task: 53113

Change-Id: I6785ff1042003271f1c8288d36159eef8c710256
Signed-off-by: Tara Nath Subedi <tara.subedi@windriver.com>