Update sysinv flake8 to use python3
Running flake8 in python3 exposes bugs that will
impact the conversion to python3.

This also adjusts the unit tests to run py36
rather than py35.

Some of the notable issues are:
 - cmp operator has been deprecated
 - file operator has been deprecated
    (replaced by call to open)

The behaviour in python2 has not changed.

For python3 unit tests should be added for:
 -  sysinv/agent/lldp/plugin.py  (Key)
sort in python3 expects a different method (__lt__)

 -  sysinv/conductor/manager.py (evaluate_app_reapply)
The contents from file open when passed to the md5 routine
should fail unless opened with utf-8 encoding
ie:
TypeError: Unicode-objects must be encoded before hashing

Change-Id: Ifcec7d5539cba2350649f56057db0f5e78ef279d
Story: 2007082
Task: 38130
Signed-off-by: Al Bailey <Al.Bailey@windriver.com>