Fix tox local UT failure. sqlite3.OperationalError
added server_default parameter to migration script
131_kube_upgrade_add_recovery_attempts.py

My local environment with:
- sqlite3 version 3.31.1
- ubuntu 20.04
- python 3.9.13

is failing tox -c ./sysinv/sysinv/sysinv/tox.ini
with the following error

sqlalchemy.exc.OperationalError: (sqlite3.OperationalError)
Cannot add a NOT NULL column with default value NULL
[SQL: '\nALTER TABLE kube_upgrade ADD recovery_attempts
INTEGER NOT NULL']
(Background on this error at: http://sqlalche.me/e/e3q8)

The zuul environment is passing I suspect because its using a different
version of sqlite3

prior to commit e571db23 Add retry for "system kube-upgrade-abort"
the local tox run was working

Test plan:

run tox locally and pass 100%

Change-Id: Ia80c928b222463be743658dc433bf5bdb1235dd7
Signed-off-by: Kyale, Eliud <Eliud.Kyale@windriver.com>