Fix yaml dump in hieradata update during K8s upgrade
This fixes a regression introduced by
https://review.opendev.org/c/starlingx/config/+/958613
That change added a hieradata update path during Kubernetes upgrade
that used yaml.safe_dump without explicitly setting
default_flow_style=False.

Without default_flow_style=False, PyYAML may emit flow style YAML
for maps and sequences. In our case, the hieradata updater wrote
SR-IOV VF entries in flow style, which led to unquoted PCI address
scalars being serialized as non-strings. One observed outcome was
Puppet attempting to bind a device named 669.0 instead of real PCI
address, causing dpdk-devbind.py to fail with:

ValueError: Unknown device: 669.0. Please specify device in
"bus:slot.func" format.

This patch sets default_flow_style=False when dumping the updated
hieradata so the file is emitted in block style (expanded format). In
addition, a custom representer is added to maintain the original 'null'
values in the YAML output instead of converting them to empty fields.

Test Plan
=========

[PASS] Perform a software upgrade from the previous to the current
release on a DC system controller using vim. Perform the Kubernetes
upgrade from v1.29.2 to v1.32.2 and monitor the update of
controller-0.yaml hieradata. The YAML file format must remain in
block (expanded) style throughout the upgrade.

[PASS] Perform a software upgrade from the previous to the current
release on a DC subcloud. Perform the incremental Kubernetes upgrade
through versions v1.29.2, v1.30.6, v1.31.5, and v1.32.2, and monitor
the update of controller-0.yaml hieradata. The YAML file format must
remain in block (expanded) style throughout the upgrade.

[PASS] Repeat the test above, performing the upgrade directly from
version v1.29.2 to v1.32.2.

Closes-Bug: 2127474

Change-Id: I41b388c2229b5a97fcd61e06e660d012b1a94113
Signed-off-by: Ferdinando Terada <Ferdinando.GodoyTerada@windriver.com>