Device image upload with bmc type error
device-image-upload with --bmc or --retimer-included failed with
error: "Expecting value: line 1 column 1 (char 0)"
Note: device-image-upload WITHOUT --bmc or --retimer-included works

The parameters for 'bmc' and 'retimer_included' (ex. True or False)
are passed in as strings instead of boolean.

Unit test case passes in parameters as strings, if strtobool
conversion works it will not catch an error

Test Plan:

PASS: Intercept the data Dictionary and override values corresponding
      to their keys with the correct values.
      Then use this command to test:
     "system device-image-upload VistaCreekBravoBMCFW_Release_WW16.1.bin
     functional 8086 0b30 --bitstream-id 32 --bmc true
     --retimer-included true"
     --> Command Response:
         +------------------+--------------------------------------+
         | Property         | Value                                |
  	 +------------------+--------------------------------------+
	 | uuid             | d54038e6-4174-48e0-943e-a7bdfa1caf07 |
         | bitstream_type   | functional                           |
	 | pci_vendor       | 8086                                 |
	 | pci_device       | 0b30                                 |
         | bitstream_id     | 35                                   |
	 | key_signature    | None                                 |
	 | revoke_key_id    | None                                 |
	 | name             | None                                 |
	 | description      | None                                 |
	 | image_version    | None                                 |
	 | applied          | False                                |
	 | applied_labels   |                                      |
         | bmc              | True                                 |
         | retimer_included | True                                 |
	 +------------------+--------------------------------------+

Closes-Bug: 1980405

Signed-off-by: Mohammad Issa <mohammad.issa@windriver.com>
Change-Id: I79ea7661b1bc383df5daa6f4f93efd4df0e7bb2b